# Generated by Django 5.1.6 on 2025-03-09 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalrecord',
            name='requisition_number',
        ),
        migrations.RemoveField(
            model_name='historicalrecord',
            name='siv',
        ),
        migrations.RemoveField(
            model_name='item',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='store_receiving_voucher',
        ),
        migrations.RemoveField(
            model_name='record',
            name='requisition_number',
        ),
        migrations.RemoveField(
            model_name='record',
            name='siv',
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='issued_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.department'),
        ),
        migrations.AlterField(
            model_name='record',
            name='issued_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.department'),
        ),
    ]
