# Generated by Django 5.1.6 on 2025-03-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrestock',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='historicalrestock',
            name='store_receiving_voucher',
        ),
        migrations.RemoveField(
            model_name='restock',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='restock',
            name='store_receiving_voucher',
        ),
    ]
